# Generated by Django 4.2.7 on 2024-08-15 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('contribution', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('UI Design', 'UI Design'), ('All Above', 'All Above')], max_length=10)),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
            ],
        ),
    ]
