# Generated by Django 4.2.7 on 2025-02-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('batch_no', models.IntegerField()),
                ('contribution', models.CharField(max_length=255)),
                ('hobbies', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name_plural': 'Authentic User'},
        ),
    ]
